services:
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - web-vol:/var/www/html
    networks:
      - inception-net
    env_file:
      - .env
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web-vol:/var/www/html
    networks:
      - inception-net
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    healthcheck:
      test: ["CMD-SHELL", "/tools/check.sh"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - inception-net
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    restart: always
  vsftpd:
    build: requirements/bonus/vsftpd
    container_name: vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    networks:
      - inception-net
    volumes:
      - web-vol:/home/ftpsecure/
    env_file:
      - .env
  redis:
    build: requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception-net
networks:
  inception-net:
volumes:
  web-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/niko/data/web-vol
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/niko/data/db-data