services:
  wordpress:
    build: srcs/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - web-vol:/var/www/html
    networks:
      - wp-net
    env_file:
      - .env
  nginx:
    build: srcs/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - web-vol:/var/www/html
    networks:
      - wp-net
  mariadb:
    build: srcs/mariadb
    container_name: mariadb
    networks:
      - wp-net
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
networks:
  wp-net:
volumes:
  web-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/niko/data/web-vol
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/niko/data/db-data