#!/bin/bash

mariadb -u root << EOF
CREATE DATABASE $MYSQL_DATABASE;
USE $MYSQL_DATABASE;
CREATE USER '$MYSQL_USERNAME'@'wordpress.$NETWORK_NAME' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME'@'wordpress.$NETWORK_NAME';
FLUSH PRIVILEGES;
EOF